-- =====================================================================
--  Migracion 049: cobertura completa del catalogo `ciudad` con DIVIPOLA
--  (division politico-administrativa oficial de Colombia, ~1022 municipios
--  unicos por nombre — el propio catalogo `ciudad` no distingue departamento,
--  asi que un puñado de nombres que se repiten entre departamentos quedan
--  representados una sola vez, mismo criterio ya usado en la migracion 048).
--
--  Motivo: el selector "Ciudad de expedicion" del formulario de empleados solo
--  ofrecia las ~117 ciudades que ya habian aparecido en Excels importados, no
--  todas las ciudades posibles de Colombia. Fuente de datos: DIVIPOLA vía
--  https://raw.githubusercontent.com/marcovega/colombia-json/master/colombia.min.json
--  (1104 filas departamento+municipio, 1022 nombres unicos).
--
--  Generada automaticamente comparando el catalogo real contra DIVIPOLA por
--  nombre normalizado (sin tildes, mayusculas) — NO a mano, para evitar errores
--  de tipeo en las ~1000 filas nuevas. El catalogo actual venia con datos sucios
--  (mayusculas sin tildes, tomados tal cual del Excel por el import — ver
--  services/importEmpleadosService.js) mezclados con las ~20 filas bien
--  capitalizadas del seed original (migraciones 035/036).
--
--  Tres tipos de cambio, en este orden (para no violar la UNIQUE KEY nueva):
--  1) Fusiones: filas que ya tenian un duplicado bien escrito en el catalogo
--     (ej. "BOGOTÁ D.C" y "BOGOTÁ D.C D.C." con "Bogotá" ya existente; "RIOACHA"
--     con "RIOHACHA" ya existente) — reapuntan las 4 columnas que referencian
--     `ciudad` (igual que la migracion 048) y borran la fila sobrante.
--  2) Renombres en el mismo id: filas sin duplicado, solo con mayusculas/sin
--     tilde, se corrigen in-place (no hace falta tocar FKs porque el id no
--     cambia). Incluye 2 sinonimos reales resueltos a mano (Cartagena -> Cartagena
--     de Indias, Espinal -> El Espinal, que es como los nombra DIVIPOLA).
--  3) Altas: los municipios de DIVIPOLA que todavia no existen en ninguna forma.
--
--  Deliberadamente sin tocar (no son municipios colombianos, o el texto no
--  alcanza para saber a cual corresponden): BARQUISIMETO-LARA, CARACAS,
--  DISTRITO CAPITAL LIBERTADOR, LA GUAJIRA (es un departamento, no un municipio),
--  MARACAIBO, NINAIMA, QUITO, SAN CRISTOBAL TACHIRA, TACHIRA-SAN CRISTOBAL,
--  VENEZUELA.
--
--  Al final se agrega una UNIQUE KEY sobre `ciudad.nombre` (no existia) para que
--  el problema de ciudades duplicadas de la migracion 048 no se pueda repetir.
--
--  Ejecutar UNA sola vez.
-- =====================================================================

-- ---- 1) Fusiones: repuntar FKs y borrar la fila duplicada ----
UPDATE users_company SET ciudad_nacimiento_id = 1 WHERE ciudad_nacimiento_id = 41;
UPDATE users_company SET ciudad_expedicion_id = 1 WHERE ciudad_expedicion_id = 41;
UPDATE contrato SET ciudad_idciudad = 1 WHERE ciudad_idciudad = 41;
UPDATE direccion SET ciudad_idciudad = 1 WHERE ciudad_idciudad = 41;
DELETE FROM ciudad WHERE idciudad = 41;

UPDATE users_company SET ciudad_nacimiento_id = 1 WHERE ciudad_nacimiento_id = 51;
UPDATE users_company SET ciudad_expedicion_id = 1 WHERE ciudad_expedicion_id = 51;
UPDATE contrato SET ciudad_idciudad = 1 WHERE ciudad_idciudad = 51;
UPDATE direccion SET ciudad_idciudad = 1 WHERE ciudad_idciudad = 51;
DELETE FROM ciudad WHERE idciudad = 51;

UPDATE users_company SET ciudad_nacimiento_id = 75 WHERE ciudad_nacimiento_id = 74;
UPDATE users_company SET ciudad_expedicion_id = 75 WHERE ciudad_expedicion_id = 74;
UPDATE contrato SET ciudad_idciudad = 75 WHERE ciudad_idciudad = 74;
UPDATE direccion SET ciudad_idciudad = 75 WHERE ciudad_idciudad = 74;
DELETE FROM ciudad WHERE idciudad = 74;

-- ---- 2) Renombres in-place (mismo id, se corrige mayúsculas/tildes) ----
UPDATE ciudad SET nombre = 'Cartagena de Indias' WHERE idciudad = 5;
UPDATE ciudad SET nombre = 'Duitama' WHERE idciudad = 42;
UPDATE ciudad SET nombre = 'Boyacá' WHERE idciudad = 43;
UPDATE ciudad SET nombre = 'Turbaná' WHERE idciudad = 44;
UPDATE ciudad SET nombre = 'Cáqueza' WHERE idciudad = 46;
UPDATE ciudad SET nombre = 'Aquitania' WHERE idciudad = 47;
UPDATE ciudad SET nombre = 'Soacha' WHERE idciudad = 48;
UPDATE ciudad SET nombre = 'Honda' WHERE idciudad = 49;
UPDATE ciudad SET nombre = 'El Espinal' WHERE idciudad = 50;
UPDATE ciudad SET nombre = 'Caldas' WHERE idciudad = 53;
UPDATE ciudad SET nombre = 'Villanueva' WHERE idciudad = 54;
UPDATE ciudad SET nombre = 'Pacho' WHERE idciudad = 55;
UPDATE ciudad SET nombre = 'La Calera' WHERE idciudad = 56;
UPDATE ciudad SET nombre = 'Pivijay' WHERE idciudad = 57;
UPDATE ciudad SET nombre = 'El Colegio' WHERE idciudad = 58;
UPDATE ciudad SET nombre = 'Úmbita' WHERE idciudad = 59;
UPDATE ciudad SET nombre = 'Barbosa' WHERE idciudad = 60;
UPDATE ciudad SET nombre = 'Sogamoso' WHERE idciudad = 61;
UPDATE ciudad SET nombre = 'Pueblo Nuevo' WHERE idciudad = 62;
UPDATE ciudad SET nombre = 'San Marcos' WHERE idciudad = 63;
UPDATE ciudad SET nombre = 'Facatativá' WHERE idciudad = 65;
UPDATE ciudad SET nombre = 'Caucasia' WHERE idciudad = 66;
UPDATE ciudad SET nombre = 'Une' WHERE idciudad = 67;
UPDATE ciudad SET nombre = 'Chía' WHERE idciudad = 68;
UPDATE ciudad SET nombre = 'El Banco' WHERE idciudad = 69;
UPDATE ciudad SET nombre = 'Simijaca' WHERE idciudad = 70;
UPDATE ciudad SET nombre = 'Chimichagua' WHERE idciudad = 71;
UPDATE ciudad SET nombre = 'Tumaco' WHERE idciudad = 72;
UPDATE ciudad SET nombre = 'Milán' WHERE idciudad = 73;
UPDATE ciudad SET nombre = 'Riohacha' WHERE idciudad = 75;
UPDATE ciudad SET nombre = 'Yopal' WHERE idciudad = 77;
UPDATE ciudad SET nombre = 'Mosquera' WHERE idciudad = 78;
UPDATE ciudad SET nombre = 'San Juan de Betulia' WHERE idciudad = 79;
UPDATE ciudad SET nombre = 'Chiquinquirá' WHERE idciudad = 80;
UPDATE ciudad SET nombre = 'Zipaquirá' WHERE idciudad = 81;
UPDATE ciudad SET nombre = 'Fómeque' WHERE idciudad = 82;
UPDATE ciudad SET nombre = 'Yacopí' WHERE idciudad = 83;
UPDATE ciudad SET nombre = 'Ventaquemada' WHERE idciudad = 84;
UPDATE ciudad SET nombre = 'Cachipay' WHERE idciudad = 85;
UPDATE ciudad SET nombre = 'Mompós' WHERE idciudad = 86;
UPDATE ciudad SET nombre = 'Curumaní' WHERE idciudad = 87;
UPDATE ciudad SET nombre = 'Santa Rosa del Sur' WHERE idciudad = 88;
UPDATE ciudad SET nombre = 'Florián' WHERE idciudad = 89;
UPDATE ciudad SET nombre = 'Zetaquira' WHERE idciudad = 90;
UPDATE ciudad SET nombre = 'San Onofre' WHERE idciudad = 92;
UPDATE ciudad SET nombre = 'San José de Miranda' WHERE idciudad = 93;
UPDATE ciudad SET nombre = 'Susacón' WHERE idciudad = 94;
UPDATE ciudad SET nombre = 'Natagaima' WHERE idciudad = 95;
UPDATE ciudad SET nombre = 'Pamplona' WHERE idciudad = 96;
UPDATE ciudad SET nombre = 'Sesquilé' WHERE idciudad = 97;
UPDATE ciudad SET nombre = 'Cota' WHERE idciudad = 98;
UPDATE ciudad SET nombre = 'Suaza' WHERE idciudad = 99;
UPDATE ciudad SET nombre = 'Manaure Balcón del Cesar' WHERE idciudad = 100;
UPDATE ciudad SET nombre = 'Gachetá' WHERE idciudad = 101;
UPDATE ciudad SET nombre = 'Cumaribo' WHERE idciudad = 102;
UPDATE ciudad SET nombre = 'Gutiérrez' WHERE idciudad = 103;
UPDATE ciudad SET nombre = 'Montelíbano' WHERE idciudad = 104;
UPDATE ciudad SET nombre = 'Tibirita' WHERE idciudad = 106;
UPDATE ciudad SET nombre = 'Chocontá' WHERE idciudad = 107;
UPDATE ciudad SET nombre = 'La Jagua de Ibirico' WHERE idciudad = 109;
UPDATE ciudad SET nombre = 'San Diego' WHERE idciudad = 110;
UPDATE ciudad SET nombre = 'Algeciras' WHERE idciudad = 111;
UPDATE ciudad SET nombre = 'Vergara' WHERE idciudad = 112;
UPDATE ciudad SET nombre = 'Santander de Quilichao' WHERE idciudad = 113;
UPDATE ciudad SET nombre = 'Girardot' WHERE idciudad = 114;
UPDATE ciudad SET nombre = 'Prado' WHERE idciudad = 115;
UPDATE ciudad SET nombre = 'Granada' WHERE idciudad = 116;
UPDATE ciudad SET nombre = 'Oiba' WHERE idciudad = 117;
UPDATE ciudad SET nombre = 'Isnos' WHERE idciudad = 118;
UPDATE ciudad SET nombre = 'Valencia' WHERE idciudad = 120;
UPDATE ciudad SET nombre = 'San Sebastián de Buenavista' WHERE idciudad = 122;
UPDATE ciudad SET nombre = 'Barrancabermeja' WHERE idciudad = 123;
UPDATE ciudad SET nombre = 'Puerto Asís' WHERE idciudad = 124;
UPDATE ciudad SET nombre = 'Coyaima' WHERE idciudad = 125;
UPDATE ciudad SET nombre = 'Capitanejo' WHERE idciudad = 126;
UPDATE ciudad SET nombre = 'Chaparral' WHERE idciudad = 127;
UPDATE ciudad SET nombre = 'Carepa' WHERE idciudad = 128;
UPDATE ciudad SET nombre = 'Tierralta' WHERE idciudad = 129;
UPDATE ciudad SET nombre = 'Carmen de Apicalá' WHERE idciudad = 130;
UPDATE ciudad SET nombre = 'Becerril' WHERE idciudad = 131;
UPDATE ciudad SET nombre = 'Florencia' WHERE idciudad = 133;
UPDATE ciudad SET nombre = 'San Martín' WHERE idciudad = 134;
UPDATE ciudad SET nombre = 'Turbo' WHERE idciudad = 135;
UPDATE ciudad SET nombre = 'Mapiripán' WHERE idciudad = 137;

-- ---- 3) Altas: municipios de DIVIPOLA sin ninguna forma existente ----
INSERT INTO ciudad (nombre) VALUES
  ('Abejorral'),
  ('Ábrego'),
  ('Abriaquí'),
  ('Acacías'),
  ('Acandí'),
  ('Acevedo'),
  ('Achí'),
  ('Agrado'),
  ('Agua de Dios'),
  ('Aguachica'),
  ('Aguada'),
  ('Aguadas'),
  ('Aguazul'),
  ('Agustín Codazzi'),
  ('Aipe'),
  ('Albán'),
  ('Albania'),
  ('Alcalá'),
  ('Aldana'),
  ('Alejandría'),
  ('Algarrobo'),
  ('Almaguer'),
  ('Almeida'),
  ('Alpujarra'),
  ('Altamira'),
  ('Alto Baudó'),
  ('Altos del Rosario'),
  ('Alvarado'),
  ('Amagá'),
  ('Amalfi'),
  ('Ambalema'),
  ('Anapoima'),
  ('Ancuyá'),
  ('Andalucía'),
  ('Andes'),
  ('Angelópolis'),
  ('Angostura'),
  ('Anolaima'),
  ('Anorí'),
  ('Anserma'),
  ('Ansermanuevo'),
  ('Anzá'),
  ('Anzoátegui'),
  ('Apartadó'),
  ('Apía'),
  ('Apulo'),
  ('Aracataca'),
  ('Aranzazu'),
  ('Aratoca'),
  ('Arauca'),
  ('Arauquita'),
  ('Arbeláez'),
  ('Arboleda'),
  ('Arboledas'),
  ('Arboletes'),
  ('Arcabuco'),
  ('Arenal'),
  ('Argelia'),
  ('Ariguaní'),
  ('Arjona'),
  ('Armero'),
  ('Arroyohondo'),
  ('Astrea'),
  ('Ataco'),
  ('Ayapel'),
  ('Bagadó'),
  ('Bahía Solano'),
  ('Bajo Baudó'),
  ('Balboa'),
  ('Baranoa'),
  ('Baraya'),
  ('Barbacoas'),
  ('Barichara'),
  ('Barranca de Upía'),
  ('Barrancas'),
  ('Barranco de Loba'),
  ('Belalcázar'),
  ('Belén'),
  ('Belén de los Andaquíes'),
  ('Belén de Umbría'),
  ('Bello'),
  ('Belmira'),
  ('Beltrán'),
  ('Berbeo'),
  ('Betania'),
  ('Betéitiva'),
  ('Betulia'),
  ('Bituima'),
  ('Boavita'),
  ('Bochalema'),
  ('Bojacá'),
  ('Bojayá'),
  ('Bolívar'),
  ('Bosconia'),
  ('Brazuelo de Papayal'),
  ('Briceño'),
  ('Bucarasica'),
  ('Buenaventura'),
  ('Buenavista'),
  ('Buenos Aires'),
  ('Buesaco'),
  ('Buga'),
  ('Bugalagrande'),
  ('Buriticá'),
  ('Busbanzá'),
  ('Cabrera'),
  ('Cabuyaro'),
  ('Cáceres'),
  ('Cáchira'),
  ('Cácota'),
  ('Caicedo'),
  ('Caicedonia'),
  ('Caimito'),
  ('Cajamarca'),
  ('Cajibío'),
  ('Cajicá'),
  ('Calamar'),
  ('Calarcá'),
  ('Caldono'),
  ('California'),
  ('Calima'),
  ('Caloto'),
  ('Campamento'),
  ('Campo de la Cruz'),
  ('Campoalegre'),
  ('Campohermoso'),
  ('Canalete'),
  ('Candelaria'),
  ('Cantagallo'),
  ('Cantón de San Pablo'),
  ('Cañasgordas'),
  ('Caparrapí'),
  ('Caracolí'),
  ('Caramanta'),
  ('Carcasí'),
  ('Carmen de Carupa'),
  ('Carolina del Príncipe'),
  ('Cartagena del Chairá'),
  ('Cartago'),
  ('Carurú'),
  ('Casabianca'),
  ('Castilla la Nueva'),
  ('Cepitá'),
  ('Cereté'),
  ('Cerinza'),
  ('Cerrito'),
  ('Cerro de San Antonio'),
  ('Cértegui'),
  ('Chachagüí'),
  ('Chaguaní'),
  ('Chalán'),
  ('Chámeza'),
  ('Charalá'),
  ('Charta'),
  ('Chibolo'),
  ('Chigorodó'),
  ('Chimá'),
  ('Chinácota'),
  ('Chinavita'),
  ('Chinchiná'),
  ('Chinú'),
  ('Chipaque'),
  ('Chipatá'),
  ('Chíquiza'),
  ('Chiriguaná'),
  ('Chiscas'),
  ('Chita'),
  ('Chitagá'),
  ('Chitaraque'),
  ('Chivatá'),
  ('Chivor'),
  ('Choachí'),
  ('Cicuco'),
  ('Ciénaga'),
  ('Ciénaga de Oro'),
  ('Ciénega'),
  ('Cimitarra'),
  ('Circasia'),
  ('Cisneros'),
  ('Ciudad Bolívar'),
  ('Clemencia'),
  ('Cocorná'),
  ('Coello'),
  ('Cogua'),
  ('Colombia'),
  ('Colón'),
  ('Colosó'),
  ('Cómbita'),
  ('Concepción'),
  ('Concordia'),
  ('Condoto'),
  ('Confines'),
  ('Consacá'),
  ('Contadero'),
  ('Contratación'),
  ('Convención'),
  ('Copacabana'),
  ('Coper'),
  ('Córdoba'),
  ('Corinto');

INSERT INTO ciudad (nombre) VALUES
  ('Coromoro'),
  ('Corozal'),
  ('Corrales'),
  ('Cotorra'),
  ('Covarachía'),
  ('Coveñas'),
  ('Cravo Norte'),
  ('Cuaspud'),
  ('Cubará'),
  ('Cubarral'),
  ('Cucaita'),
  ('Cucunubá'),
  ('Cucutilla'),
  ('Cuítiva'),
  ('Cumaral'),
  ('Cumbal'),
  ('Cumbitara'),
  ('Cunday'),
  ('Curillo'),
  ('Curití'),
  ('Dabeiba'),
  ('Dagua'),
  ('Dibulla'),
  ('Distracción'),
  ('Dolores'),
  ('Donmatías'),
  ('Dosquebradas'),
  ('Duranía'),
  ('Ebéjico'),
  ('El Águila'),
  ('El Atrato'),
  ('El Bagre'),
  ('El Cairo'),
  ('El Calvario'),
  ('El Carmen'),
  ('El Carmen de Atrato'),
  ('El Carmen de Bolívar'),
  ('El Carmen de Chucurí'),
  ('El Carmen de Viboral'),
  ('El Carmen del Darién'),
  ('El Castillo'),
  ('El Cerrito'),
  ('El Charco'),
  ('El Cocuy'),
  ('El Copey'),
  ('El Doncello'),
  ('El Dorado'),
  ('El Dovio'),
  ('El Espino'),
  ('El Guacamayo'),
  ('El Guamo'),
  ('El Molino'),
  ('El Paso'),
  ('El Paujil'),
  ('El Peñol'),
  ('El Peñón'),
  ('El Piñón'),
  ('El Pital'),
  ('El Playón'),
  ('El Retén'),
  ('El Retiro'),
  ('El Retorno'),
  ('El Roble'),
  ('El Rosal'),
  ('El Rosario'),
  ('El Santuario'),
  ('El Socorro'),
  ('El Tablón'),
  ('El Tambo'),
  ('El Tarra'),
  ('El Zulia'),
  ('Elías'),
  ('Encino'),
  ('Enciso'),
  ('Entrerríos'),
  ('Envigado'),
  ('Falán'),
  ('Filadelfia'),
  ('Filandia'),
  ('Firavitoba'),
  ('Flandes'),
  ('Floresta'),
  ('Florida'),
  ('Floridablanca'),
  ('Fonseca'),
  ('Fortul'),
  ('Fosca'),
  ('Francisco Pizarro'),
  ('Fredonia'),
  ('Fresno'),
  ('Frontino'),
  ('Fuente de Oro'),
  ('Fundación'),
  ('Funes'),
  ('Funza'),
  ('Fúquene'),
  ('Fusagasugá'),
  ('Gachalá'),
  ('Gachancipá'),
  ('Gachantivá'),
  ('Galán'),
  ('Galapa'),
  ('Galeras'),
  ('Gama'),
  ('Gamarra'),
  ('Gámbita'),
  ('Gámeza'),
  ('Garagoa'),
  ('Garzón'),
  ('Génova'),
  ('Gigante'),
  ('Ginebra'),
  ('Giraldo'),
  ('Girardota'),
  ('Girón'),
  ('Gómez Plata'),
  ('González'),
  ('Gramalote'),
  ('Guaca'),
  ('Guacamayas'),
  ('Guacarí'),
  ('Guachené'),
  ('Guachetá'),
  ('Guachucal'),
  ('Guadalupe'),
  ('Guaduas'),
  ('Guaitarilla'),
  ('Gualmatán'),
  ('Guamal'),
  ('Guamo'),
  ('Guapí'),
  ('Guapotá'),
  ('Guaranda'),
  ('Guarne'),
  ('Guasca'),
  ('Guatapé'),
  ('Guataquí'),
  ('Guatavita'),
  ('Guateque'),
  ('Guática'),
  ('Guavatá'),
  ('Guayabal de Síquima'),
  ('Guayabetal'),
  ('Guayatá'),
  ('Güepsa'),
  ('Güicán'),
  ('Hacarí'),
  ('Hatillo de Loba'),
  ('Hato'),
  ('Hato Corozal'),
  ('Hatonuevo'),
  ('Heliconia'),
  ('Herrán'),
  ('Herveo'),
  ('Hispania'),
  ('Hobo'),
  ('Icononzo'),
  ('Iles'),
  ('Imués'),
  ('Inírida'),
  ('Inzá'),
  ('Ipiales'),
  ('Íquira'),
  ('Istmina'),
  ('Itagüí'),
  ('Ituango'),
  ('Iza'),
  ('Jambaló'),
  ('Jamundí'),
  ('Jardín'),
  ('Jenesano'),
  ('Jericó'),
  ('Jerusalén'),
  ('Jesús María'),
  ('Jordán'),
  ('Juan de Acosta'),
  ('Junín'),
  ('Juradó'),
  ('La Apartada'),
  ('La Argentina'),
  ('La Belleza'),
  ('La Capilla'),
  ('La Ceja'),
  ('La Celia'),
  ('La Cruz'),
  ('La Cumbre'),
  ('La Dorada'),
  ('La Esperanza'),
  ('La Estrella'),
  ('La Florida'),
  ('La Gloria (Cesar)'),
  ('La Jagua del Pilar'),
  ('La Llanada'),
  ('La Macarena'),
  ('La Merced'),
  ('La Mesa'),
  ('La Montañita'),
  ('La Palma'),
  ('La Paz'),
  ('La Peña');

INSERT INTO ciudad (nombre) VALUES
  ('La Pintada'),
  ('La Plata'),
  ('La Playa de Belén'),
  ('La Primavera'),
  ('La Salina'),
  ('La Sierra'),
  ('La Tebaida'),
  ('La Tola'),
  ('La Unión'),
  ('La Uribe'),
  ('La Uvita'),
  ('La Vega'),
  ('La Victoria'),
  ('La Virginia'),
  ('Labateca'),
  ('Labranzagrande'),
  ('Landázuri'),
  ('Lebrija'),
  ('Leiva'),
  ('Lejanías'),
  ('Lenguazaque'),
  ('Lérida'),
  ('Leticia'),
  ('Líbano'),
  ('Liborina'),
  ('Linares'),
  ('Litoral de San Juan'),
  ('Lloró'),
  ('López de Micay'),
  ('Lorica'),
  ('Los Andes'),
  ('Los Córdobas'),
  ('Los Palmitos'),
  ('Los Patios'),
  ('Los Santos'),
  ('Lourdes'),
  ('Luruaco'),
  ('Macanal'),
  ('Macaravita'),
  ('Maceo'),
  ('Machetá'),
  ('Madrid'),
  ('Magangué'),
  ('Magüí Payán'),
  ('Mahates'),
  ('Maicao'),
  ('Majagual'),
  ('Málaga'),
  ('Malambo'),
  ('Mallama'),
  ('Manatí'),
  ('Manaure'),
  ('Maní'),
  ('Manta'),
  ('Manzanares'),
  ('Margarita'),
  ('María la Baja'),
  ('Marinilla'),
  ('Maripí'),
  ('Mariquita'),
  ('Marmato'),
  ('Marquetalia'),
  ('Marsella'),
  ('Marulanda'),
  ('Matanza'),
  ('Medina'),
  ('Medio Atrato'),
  ('Medio Baudó'),
  ('Medio San Juan'),
  ('Melgar'),
  ('Mercaderes'),
  ('Mesetas'),
  ('Miraflores'),
  ('Miranda'),
  ('Mistrató'),
  ('Mitú'),
  ('Mocoa'),
  ('Mogotes'),
  ('Molagavita'),
  ('Momil'),
  ('Mongua'),
  ('Monguí'),
  ('Moniquirá'),
  ('Montebello'),
  ('Montecristo'),
  ('Montenegro'),
  ('Monterrey'),
  ('Moñitos'),
  ('Morales'),
  ('Morelia'),
  ('Morroa'),
  ('Motavita'),
  ('Murillo'),
  ('Murindó'),
  ('Mutatá'),
  ('Mutiscua'),
  ('Muzo'),
  ('Nariño'),
  ('Nátaga'),
  ('Nechí'),
  ('Necoclí'),
  ('Neira'),
  ('Nemocón'),
  ('Nilo'),
  ('Nimaima'),
  ('Nobsa'),
  ('Nocaima'),
  ('Norcasia'),
  ('Norosí'),
  ('Nóvita'),
  ('Nueva Granada'),
  ('Nuevo Colón'),
  ('Nunchía'),
  ('Nuquí'),
  ('Obando'),
  ('Ocamonte'),
  ('Ocaña'),
  ('Oicatá'),
  ('Olaya'),
  ('Olaya Herrera'),
  ('Onzaga'),
  ('Oporapa'),
  ('Orito'),
  ('Orocué'),
  ('Ortega'),
  ('Ospina'),
  ('Otanche'),
  ('Ovejas'),
  ('Pachavita'),
  ('Pácora'),
  ('Padilla'),
  ('Páez'),
  ('Paicol'),
  ('Pailitas'),
  ('Paime'),
  ('Paipa'),
  ('Pajarito'),
  ('Palermo'),
  ('Palestina'),
  ('Palmar'),
  ('Palmar de Varela'),
  ('Palmas del Socorro'),
  ('Palmira'),
  ('Palocabildo'),
  ('Pamplonita'),
  ('Pandi'),
  ('Panqueba'),
  ('Páramo'),
  ('Paratebueno'),
  ('Pasca'),
  ('Patía'),
  ('Pauna'),
  ('Paya'),
  ('Paz de Ariporo'),
  ('Paz del Río'),
  ('Pedraza'),
  ('Pelaya'),
  ('Pensilvania'),
  ('Peque'),
  ('Pesca'),
  ('Piamonte'),
  ('Piedecuesta'),
  ('Piedras'),
  ('Piendamó'),
  ('Pijao'),
  ('Pijiño del Carmen'),
  ('Pinchote'),
  ('Pinillos'),
  ('Piojó'),
  ('Pisba'),
  ('Pitalito'),
  ('Planadas'),
  ('Planeta Rica'),
  ('Plato'),
  ('Policarpa'),
  ('Polonuevo'),
  ('Ponedera'),
  ('Pore'),
  ('Potosí'),
  ('Pradera'),
  ('Providencia'),
  ('Providencia y Santa Catalina Islas'),
  ('Pueblo Bello'),
  ('Pueblo Rico'),
  ('Pueblo Viejo'),
  ('Pueblorrico'),
  ('Puente Nacional'),
  ('Puerres'),
  ('Puerto Berrío'),
  ('Puerto Boyacá'),
  ('Puerto Caicedo'),
  ('Puerto Carreño'),
  ('Puerto Colombia'),
  ('Puerto Concordia'),
  ('Puerto Escondido'),
  ('Puerto Gaitán'),
  ('Puerto Guzmán'),
  ('Puerto Leguízamo'),
  ('Puerto Libertador'),
  ('Puerto Lleras');

INSERT INTO ciudad (nombre) VALUES
  ('Puerto López'),
  ('Puerto Nare'),
  ('Puerto Nariño'),
  ('Puerto Parra'),
  ('Puerto Rico'),
  ('Puerto Rondón'),
  ('Puerto Salgar'),
  ('Puerto Santander'),
  ('Puerto Tejada'),
  ('Puerto Triunfo'),
  ('Puerto Wilches'),
  ('Pulí'),
  ('Pupiales'),
  ('Puracé'),
  ('Purificación'),
  ('Purísima'),
  ('Quebradanegra'),
  ('Quetame'),
  ('Quibdó'),
  ('Quimbaya'),
  ('Quinchía'),
  ('Quípama'),
  ('Quipile'),
  ('Ragonvalia'),
  ('Ramiriquí'),
  ('Ráquira'),
  ('Recetor'),
  ('Regidor'),
  ('Remedios'),
  ('Remolino'),
  ('Repelón'),
  ('Restrepo'),
  ('Ricaurte'),
  ('Río de Oro'),
  ('Río Iró'),
  ('Río Quito'),
  ('Río Viejo'),
  ('Rioblanco'),
  ('Riofrío'),
  ('Rionegro'),
  ('Riosucio'),
  ('Risaralda'),
  ('Rivera'),
  ('Roberto Payán'),
  ('Roldanillo'),
  ('Roncesvalles'),
  ('Rondón'),
  ('Rosas'),
  ('Rovira'),
  ('Sabana de Torres'),
  ('Sabanagrande'),
  ('Sabanalarga'),
  ('Sabanas de San Ángel'),
  ('Sabaneta'),
  ('Saboyá'),
  ('Sácama'),
  ('Sáchica'),
  ('Sahagún'),
  ('Saladoblanco'),
  ('Salamina'),
  ('Salazar de Las Palmas'),
  ('Saldaña'),
  ('Salento'),
  ('Salgar'),
  ('Samacá'),
  ('Samaná'),
  ('Samaniego'),
  ('Sampués'),
  ('San Agustín'),
  ('San Alberto'),
  ('San Andrés'),
  ('San Andrés de Cuerquia'),
  ('San Andrés de Sotavento'),
  ('San Antero'),
  ('San Antonio'),
  ('San Antonio de Palmito'),
  ('San Antonio del Tequendama'),
  ('San Benito'),
  ('San Benito Abad'),
  ('San Bernardo'),
  ('San Bernardo del Viento'),
  ('San Calixto'),
  ('San Carlos'),
  ('San Carlos de Guaroa'),
  ('San Cayetano'),
  ('San Cristóbal'),
  ('San Eduardo'),
  ('San Estanislao'),
  ('San Fernando'),
  ('San Francisco'),
  ('San Gil'),
  ('San Jacinto'),
  ('San Jacinto del Cauca'),
  ('San Jerónimo'),
  ('San Joaquín'),
  ('San José'),
  ('San José de Albán'),
  ('San José de la Montaña'),
  ('San José de Pare'),
  ('San José de Uré'),
  ('San José del Fragua'),
  ('San José del Guaviare'),
  ('San José del Palmar'),
  ('San Juan de Arama'),
  ('San Juan de Rioseco'),
  ('San Juan de Urabá'),
  ('San Juan del Cesar'),
  ('San Juan Nepomuceno'),
  ('San Juanito'),
  ('San Lorenzo'),
  ('San Luis'),
  ('San Luis de Gaceno'),
  ('San Luis de Palenque'),
  ('San Martín de Loba'),
  ('San Mateo'),
  ('San Miguel'),
  ('San Miguel de Sema'),
  ('San Pablo'),
  ('San Pablo de Borbur'),
  ('San Pedro'),
  ('San Pedro de Cartago'),
  ('San Pedro de los Milagros'),
  ('San Pedro de Urabá'),
  ('San Pelayo'),
  ('San Rafael'),
  ('San Roque'),
  ('San Sebastián'),
  ('San Vicente'),
  ('San Vicente de Chucurí'),
  ('San Vicente del Caguán'),
  ('San Zenón'),
  ('Sandoná'),
  ('Santa Ana'),
  ('Santa Bárbara'),
  ('Santa Bárbara de Pinto'),
  ('Santa Catalina'),
  ('Santa Fe de Antioquia'),
  ('Santa Helena del Opón'),
  ('Santa Isabel'),
  ('Santa Lucía'),
  ('Santa María'),
  ('Santa Rosa'),
  ('Santa Rosa de Cabal'),
  ('Santa Rosa de Osos'),
  ('Santa Rosa de Viterbo'),
  ('Santa Rosalía'),
  ('Santa Sofía'),
  ('Santacruz'),
  ('Santana'),
  ('Santiago'),
  ('Santo Domingo'),
  ('Santo Domingo de Silos'),
  ('Santo Tomás'),
  ('Santuario'),
  ('Sapuyes'),
  ('Saravena'),
  ('Sardinata'),
  ('Sasaima'),
  ('Sativanorte'),
  ('Sativasur'),
  ('Segovia'),
  ('Sevilla'),
  ('Siachoque'),
  ('Sibaté'),
  ('Sibundoy'),
  ('Silvania'),
  ('Silvia'),
  ('Simacota'),
  ('Simití'),
  ('Sincé'),
  ('Sipí'),
  ('Sitionuevo'),
  ('Soatá'),
  ('Socha'),
  ('Socotá'),
  ('Solano'),
  ('Soledad'),
  ('Solita'),
  ('Somondoco'),
  ('Sonsón'),
  ('Sopetrán'),
  ('Soplaviento'),
  ('Sopó'),
  ('Sora'),
  ('Soracá'),
  ('Sotaquirá'),
  ('Sotará'),
  ('Suaita'),
  ('Suán'),
  ('Suárez'),
  ('Subachoque'),
  ('Sucre'),
  ('Suesca'),
  ('Supatá'),
  ('Supía'),
  ('Suratá'),
  ('Susa'),
  ('Sutamarchán'),
  ('Sutatausa'),
  ('Sutatenza');

INSERT INTO ciudad (nombre) VALUES
  ('Tabio'),
  ('Tadó'),
  ('Talaigua Nuevo'),
  ('Tamalameque'),
  ('Támara'),
  ('Tame'),
  ('Támesis'),
  ('Taminango'),
  ('Tangua'),
  ('Taraira'),
  ('Tarazá'),
  ('Tarqui'),
  ('Tarso'),
  ('Tasco'),
  ('Tauramena'),
  ('Tausa'),
  ('Tello'),
  ('Tena'),
  ('Tenerife'),
  ('Tenjo'),
  ('Tenza'),
  ('Teorama'),
  ('Teruel'),
  ('Tesalia'),
  ('Tibacuy'),
  ('Tibaná'),
  ('Tibasosa'),
  ('Tibú'),
  ('Timaná'),
  ('Timbío'),
  ('Timbiquí'),
  ('Tinjacá'),
  ('Tipacoque'),
  ('Tiquisio'),
  ('Titiribí'),
  ('Toca'),
  ('Tocaima'),
  ('Tocancipá'),
  ('Togüí'),
  ('Toledo'),
  ('Tolú'),
  ('Tolú Viejo'),
  ('Tona'),
  ('Tópaga'),
  ('Topaipí'),
  ('Toribío'),
  ('Toro'),
  ('Tota'),
  ('Totoró'),
  ('Trinidad'),
  ('Trujillo'),
  ('Tubará'),
  ('Tuchín'),
  ('Tuluá'),
  ('Tununguá'),
  ('Túquerres'),
  ('Turbaco'),
  ('Turmequé'),
  ('Tuta'),
  ('Tutazá'),
  ('Ubalá'),
  ('Ubaque'),
  ('Ubaté'),
  ('Ulloa'),
  ('Unguía'),
  ('Unión Panamericana'),
  ('Uramita'),
  ('Uribia'),
  ('Urrao'),
  ('Urumita'),
  ('Usiacurí'),
  ('Útica'),
  ('Valdivia'),
  ('Valle de San José'),
  ('Valle de San Juan'),
  ('Valle del Guamuez'),
  ('Valparaíso'),
  ('Vegachí'),
  ('Vélez'),
  ('Venadillo'),
  ('Venecia'),
  ('Versalles'),
  ('Vetas'),
  ('Vianí'),
  ('Victoria'),
  ('Vigía del Fuerte'),
  ('Vijes'),
  ('Villa Caro'),
  ('Villa de Leyva'),
  ('Villa del Rosario'),
  ('Villa Rica'),
  ('Villagarzón'),
  ('Villagómez'),
  ('Villahermosa'),
  ('Villamaría'),
  ('Villapinzón'),
  ('Villarrica'),
  ('Villavieja'),
  ('Villeta'),
  ('Viotá'),
  ('Viracachá'),
  ('Vista Hermosa'),
  ('Viterbo'),
  ('Yacuanquer'),
  ('Yaguará'),
  ('Yalí'),
  ('Yarumal'),
  ('Yolombó'),
  ('Yondó'),
  ('Yotoco'),
  ('Yumbo'),
  ('Zambrano'),
  ('Zapatoca'),
  ('Zapayán'),
  ('Zaragoza'),
  ('Zarzal'),
  ('Zipacón'),
  ('Zona Bananera');

-- ---- 4) Blindaje: nunca más un nombre duplicado ----
ALTER TABLE ciudad ADD UNIQUE KEY uq_ciudad_nombre (nombre);
